export const LIST_CAROUSEL_PICS_REQUEST = 'LIST_CAROUSEL_PICS_REQUEST'
export const LIST_CAROUSEL_PICS_SUCCESS = 'LIST_CAROUSEL_PICS_SUCCESS'
export const LIST_CAROUSEL_PICS_FAIL = 'LIST_CAROUSEL_PICS_FAIL'
