export const PRODUCTS_LIST_REQUEST = 'PRODUCTS_LIST_REQUEST'
export const PRODUCTS_LIST_SUCCESS = 'PRODUCTS_LIST_SUCCESS'
export const PRODUCTS_LIST_FAIL = 'PRODUCTS_LIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_INSLIDE_REQUEST = 'PRODUCT_INSLIDE_REQUEST'
export const PRODUCT_INSLIDE_SUCCESS = 'PRODUCT_INSLIDE_SUCCESS'
export const PRODUCT_INSLIDE_FAIL = 'PRODUCT_INSLIDE_FAIL'

export const FEATURED_PRODUCTS_REQUEST = 'FEATURED_PRODUCTS_REQUEST'
export const FEATURED_PRODUCTS_SUCCESS = 'FEATURED_PRODUCTS_SUCCESS'
export const FEATURED_PRODUCTS_FAIL = 'FEATURED_PRODUCTS_FAIL'
